stages:
  - build

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/walrusnetwork/infrastructure/snout .
    - docker push $CI_REGISTRY/walrusnetwork/infrastructure/snout
